replicaCount: 1

backend:
  image:
    repository: hoteling-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5126
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  image:
    repository: hoteling-web
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

ingress:
  enabled: true
  className: nginx
  host: hoteling.local
  annotations: {}
